---
abstract: 'Polymorphic Loci analysis'
author:
  - 'Luis M. Rodriguez-R <lmrodriguezr@gmail.com>'
build_requires:
  Module::Build: 0.2
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3622'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio::Polloc
provides:
  Bio::Polloc::Genome:
    file: lib/Bio/Polloc/Genome.pm
  Bio::Polloc::GroupCriteria:
    file: lib/Bio/Polloc/GroupCriteria.pm
  Bio::Polloc::GroupCriteria::operator:
    file: lib/Bio/Polloc/GroupCriteria/operator.pm
  Bio::Polloc::GroupCriteria::operator::bool:
    file: lib/Bio/Polloc/GroupCriteria/operator/bool.pm
  Bio::Polloc::GroupCriteria::operator::cons:
    file: lib/Bio/Polloc/GroupCriteria/operator/cons.pm
  Bio::Polloc::GroupCriteria::operator::num:
    file: lib/Bio/Polloc/GroupCriteria/operator/num.pm
  Bio::Polloc::GroupCriteria::operator::seq:
    file: lib/Bio/Polloc/GroupCriteria/operator/seq.pm
  Bio::Polloc::LociGroup:
    file: lib/Bio/Polloc/LociGroup.pm
  Bio::Polloc::Locus::amplicon:
    file: lib/Bio/Polloc/Locus/amplicon.pm
  Bio::Polloc::Locus::composition:
    file: lib/Bio/Polloc/Locus/composition.pm
  Bio::Polloc::Locus::crispr:
    file: lib/Bio/Polloc/Locus/crispr.pm
  Bio::Polloc::Locus::extend:
    file: lib/Bio/Polloc/Locus/extend.pm
  Bio::Polloc::Locus::generic:
    file: lib/Bio/Polloc/Locus/generic.pm
  Bio::Polloc::Locus::pattern:
    file: lib/Bio/Polloc/Locus/pattern.pm
  Bio::Polloc::Locus::repeat:
    file: lib/Bio/Polloc/Locus/repeat.pm
  Bio::Polloc::LocusI:
    file: lib/Bio/Polloc/LocusI.pm
  Bio::Polloc::LocusIO:
    file: lib/Bio/Polloc/LocusIO.pm
  Bio::Polloc::LocusIO::gff3:
    file: lib/Bio/Polloc/LocusIO/gff3.pm
  Bio::Polloc::Polloc::Config:
    file: lib/Bio/Polloc/Polloc/Config.pm
  Bio::Polloc::Polloc::Error:
    file: lib/Bio/Polloc/Polloc/Error.pm
  Bio::Polloc::Polloc::IO:
    file: lib/Bio/Polloc/Polloc/IO.pm
  Bio::Polloc::Polloc::Root:
    file: lib/Bio/Polloc/Polloc/Root.pm
    version: 1.0500
  Bio::Polloc::Rule::boolean:
    file: lib/Bio/Polloc/Rule/boolean.pm
  Bio::Polloc::Rule::composition:
    file: lib/Bio/Polloc/Rule/composition.pm
  Bio::Polloc::Rule::crispr:
    file: lib/Bio/Polloc/Rule/crispr.pm
  Bio::Polloc::Rule::pattern:
    file: lib/Bio/Polloc/Rule/pattern.pm
  Bio::Polloc::Rule::profile:
    file: lib/Bio/Polloc/Rule/profile.pm
  Bio::Polloc::Rule::repeat:
    file: lib/Bio/Polloc/Rule/repeat.pm
  Bio::Polloc::Rule::tandemrepeat:
    file: lib/Bio/Polloc/Rule/tandemrepeat.pm
  Bio::Polloc::RuleI:
    file: lib/Bio/Polloc/RuleI.pm
  Bio::Polloc::RuleIO:
    file: lib/Bio/Polloc/RuleIO.pm
  Bio::Polloc::RuleSet::cfg:
    file: lib/Bio/Polloc/RuleSet/cfg.pm
  Bio::Polloc::Typing::bandingPattern:
    file: lib/Bio/Polloc/Typing/bandingPattern.pm
  Bio::Polloc::Typing::bandingPattern::amplification:
    file: lib/Bio/Polloc/Typing/bandingPattern/amplification.pm
  Bio::Polloc::TypingI:
    file: lib/Bio/Polloc/TypingI.pm
  Bio::Polloc::TypingIO:
    file: lib/Bio/Polloc/TypingIO.pm
  Bio::Polloc::TypingIO::cfg:
    file: lib/Bio/Polloc/TypingIO/cfg.pm
recommends:
  Bio::Tools::Run::Alignment::Muscle: 0
  Bio::Tools::Run::Hmmer: 0
  Bio::Tools::Run::StandAloneBlast: 0
  Cwd: 0
  File::Basename: 0
  GD::Simple: 0
requires:
  Bio::SeqIO: 0
  Error: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  List::Util: 0
  Symbol: 0
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0500
